apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aquawatch
  namespace: aquawatch
spec:
  selector:
    matchLabels:
      app: aquawatch
  endpoints:
  - port: api
    path: /metrics
    interval: 30s
