apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aquawatch-models
  namespace: aquawatch
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aquawatch-data
  namespace: aquawatch
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-client
  resources:
    requests:
      storage: 50Gi
